### PR TITLE
Add roles

### PR DESCRIPTION
**Pull request by Kotty666**
This commit adds the posibility to use the 3EM also as genset and ac-load Sensor

### CODE REVIEW

**Comment by stenub** [comment]
Hi @Kotty666, i put your acload branch on my VenusOS in the /data path, changed the role to grid, and expected the Shelly to show up as "Grid" in the Remote Console and the VRM Portal. Unfortunately, there is still "AC Input" in the remote console and VRM. In the VRM there also is no sum over L1,L2,L3 shown but i am not sure if this is really a problem of the dbus driver. Could be the VRM itself, as my multiplus is still waitint for shippment.
How can i get the shelly to show up as grid?

**Comment by Kotty666** [comment]
@stenub 
i think this in issue with vrm - at my Installation there are also a 3EM as Grid - at the Venus it shows the AC-Input with eache phase an correctly Calculatet and at the vrm the Sum is missing at AC-Input but the Phases are shown correctly
How is it displayed at your venusOS interface?

**Comment by stenub** [comment]
@Kotty666 Mine looks exactly as yours.. Do you have a Multiplus running or just a shelly and a venus os device? I think it could be the missing Multiplus that makes the vrm showing the grid as ac input. I have ordered a multiplus, hopefully it gets delivered the upcoming weeks.

**Comment by Kotty666** [comment]
@stenub, at the moment there is no MP running only VenusOS on Raspi, 2 Shelly EM3 and a Growatt Inverter. I'll hope the MPs will be installed soon :)

**Comment by Kotty666** [comment]
@fabian-lauer did you have time to check the MR?

**Comment by fabian-lauer** [comment]
@Kotty666 I merged the other PR, but looks like all your changes are in "main" now.
Will close this PR

**Pull request closed without merging**
