### PR TITLE
added logging options

### PR DESCRIPTION
**Pull request by Kotty666**
i've added the logrotation. So the logfile will have a maximum of 50MB, 2 old will be saved.

### CODE REVIEW

**Comment by fabian-lauer** [comment]
@Kotty666 sorry for my late reply - those changes looked good but I didn't realize that the "logging.handler" is not included in default Victrons GX device.
Can you confirm or offer an alternative?

**Comment by Kotty666** [comment]
Add the moment i've no posibilty to connect to a cerbo gx :( 
Which Firmware Version did the GX Device running?

**Comment by fabian-lauer** [comment]
Running on v2.90

**Comment by Kotty666** [comment]
Really strange, which error did you get?
I've extracted the Disk-image and there i see the handlers extension (same version as in the RaspberryPi Image 2.92)

**Pull request merged**
